name: 'Build Chat'
description: 'Notify in chat about build results.'
author: 'Christof Marti'
inputs:
  token:
    description: GitHub token.
    default: ${{ github.token }}
    required: true
  slack_token:
    description: Slack token.
    required: true
  storage_connection_string:
    description: Storage connection string.
    required: false
  workflow_run_url:
    description: 'Workflow run URL of the completed build.'
    required: true
  notify_authors:
    description: 'Whether the notifications should be sent directly to users. Defaults to false.'
    required: false
  notification_channel:
    description: 'Which channel to send notifications to. Defaults to none.'
    required: false
  log_channel:
    description: 'Which channel to send log messages to. Defaults to none.'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
